name: Go Cross-Platform Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
          - os: windows-latest
            goos: windows
          - os: macos-latest
            goos: darwin
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Install Linux GUI dependencies
      if: matrix.goos == 'linux'
      run: |
        sudo apt update
        sudo apt install -y \
        libx11-dev \
        libx11-xcb-dev \
        libxkbcommon-dev \
        libxkbcommon-x11-dev \
        libxcursor-dev \
        libxfixes-dev \
        libwayland-dev \
        pkg-config \
        libegl1-mesa-dev \
        libgl1-mesa-dev \
        libvulkan-dev




    - name: Ensure Xcode tools
      if: matrix.goos == 'darwin'
      run: xcode-select --install || true



    - name: Install dependencies
      if: matrix.goos == 'linux'
      run: go mod tidy

    - name: Download dependencies
      run: go mod download

    - name: Build Linux
      if: matrix.goos == 'linux'
      run: go build -o VPDesktop

    - name: Build Windows
      if: matrix.goos == 'windows'
      run: go build -ldflags="-H=windowsgui" -o VPDesktop.exe
      shell: bash

    - name: Build macOS
      if: matrix.goos == 'darwin'
      run: go build -o VPDesktop


    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: vpdesktop-${{ matrix.goos }}
        path: ${{ matrix.goos == 'windows' && 'VPDesktop.exe' || 'VPDesktop' }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate date-based version
        id: get_version
        run: |
          tag=$(date +release-%d:%m:%Y-%H:%M)
          name=$(date +Release\ %d.%m.%Y\ %H:%M)

          echo "tag_name=$tag" >> $GITHUB_OUTPUT
          echo "release_name=$name" >> $GITHUB_OUTPUT
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: Build ${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: VPDesktop-linux
          path: ./artifacts/linux
      - uses: actions/download-artifact@v4
        with:
          name: VPDesktop-windows
          path: ./artifacts/windows
      - uses: actions/download-artifact@v4
        with:
          name: VPDesktop-darwin
          path: ./artifacts/macos


      - name: Upload Linux artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/linux/VPDesktop
          asset_name: VPDesktop-linux
          asset_content_type: application/octet-stream

      - name: Upload Windows artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/windows/VPDesktop.exe
          asset_name: VPDesktop-windows.exe
          asset_content_type: application/octet-stream

      - name: Upload macOS artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/macos/VPDesktop
          asset_name: VPDesktop-macos
          asset_content_type: application/octet-stream
